import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './components/NavBar';
import '@mantine/core/styles.css';
import '@mantine/tiptap/styles.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Journal App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' data-theme='dark'>
            <head>
                <ColorSchemeScript defaultColorScheme='dark' />
            </head>
            <body className={inter.className}>
                <NavBar />
                <MantineProvider defaultColorScheme='dark'>
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
}
